apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::509002973204:role/eksctl-eks-cube-test-nodegroup-ek-NodeInstanceRole-1OBGFENRQAYOW
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::509002973204:role/eksctl-eks-cube-test-nodegroup-ek-NodeInstanceRole-38EYOEVV1T73
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      - system:nodes
      rolearn: arn:aws:iam::509002973204:role/cubejs-eks-role
      username: cubejs-eks-role
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2023-02-13T11:37:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2593"
  uid: 4463b02b-9e1d-4a88-a339-9cac9c522fd0
